'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BankingSoftware.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _032() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("032", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _0321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _10005000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("10005000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1000nt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1000nt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _100nn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("100nn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property a1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("a1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property a3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("a3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property a4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("a4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property a5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("a5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ANZ_Bank_counter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ANZ-Bank-counter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ANZ_Bank_counter1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ANZ-Bank-counter1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bank_dc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bank_dc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property closemy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("closemy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gamla() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gamla", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ggg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ggg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ggg1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ggg1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Login_Button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Login-Button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property login_img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login_img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mainpic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mainpic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property money_exchange_in_goa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("money-exchange-in-goa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property moneyPix() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("moneyPix", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property processing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("processing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property title() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("title", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property welcome() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("welcome", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
